spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rent_your_room_db
    username: postgres
    password: BOBY@mechal1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

rent:
  your:
    room:
      jwtSecret: "=======================RentYourRoomJWTSecret==========================="
      jwtExpirationMs: 86400000
      app:
        jwtRefreshExpirationMs: 86400000
